spring.application.name=backend
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=priscakebi00@gmail.com
spring.mail.password=wtoh bmnc jsax zges
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true